### PR TITLE
Valgrind memory leak fixes

### PR DESCRIPTION
**Pull request by sanskriti-s**
Fixes valgrind warnings when running:
```
valgrind --leak-check=full --show-leak-kinds=all .libs/numademo -t -e 1M
```

### CODE REVIEW

**Comment by joe-lawrence** [comment]
"libnuma: cleanup nodemask in destructor"
- I justed noticed closed issue #3, though it seems trivial to clean up this data structure along with the bitmask pointers.  Leave it up to the maintainer(s) whether to keep or drop this change from the series.
- If we're gonna keep it, some small terminology / placement suggestions.  The commit message, function name and code placement should be related to "cpu mask" and not "node mask". i.e.
-- Rename `numa_cleanup_nodemask` to `cleanup_node_cpu_mask_v2`
-- move `cleanup_node_cpu_mask_v2()` to just below its `init_node_cpu_mask_v2()` counterpart
-- update commit msg accordingly

-- Joe

**Comment by andikleen** [comment]
Can you remove the free() on error exits in numademo? That's too ugly. Freeing on normal exit is ok.
For the new clean up function in libnuma.c please follow the coding style: function prototype on single line, spaces around operators

**Comment by sanskriti-s** [comment]
v2:
- "cpu node mask" renames (@joe-lawrence's)
- dropped numademo error path frees (@andikleen)
- libnuma style fixups: one line function prototype, spaces around
operators in for() loop. (@andikleen)

**Comment by andikleen** [comment]
Thanks!

**Pull request merged**
