### PR TITLE
numactl: add support for new 'prefer-many-nodes' policy

### PR DESCRIPTION
**Pull request by ftang1**
Linux kernel 5.15 has merged a new memory policy "MPOL_PREFERRED_MANY", which allows user to specified multiple nodes as the preferred list to first allocate memory from, and till there is no available memory on those nodes, it will fallback to all other memory nodes in system.

This patchset adds the support in numactl/libnuma, and user can chose this policy by:

   numactl [--preferred-many= | -P <nodes>]

And with older kernel, it will return with warning message:
  "numactl: preferred-many requested without kernel support"

### CODE REVIEW

**Review by andikleen — CHANGES_REQUESTED** [review]
Assert is not the right way to check for allocation failure
Seems to have a memory leak on tmp?

**Review by andikleen — CHANGES_REQUESTED** [review]
Please use preferred-many and use the same in the print output

**Comment by andikleen** [comment]
I don't see any additions to the test suite? Need test coverage

**Comment by ftang1** [comment]
Andi, thanks for the reviews! and sorry for the delay, I just saw these messages (my github email is a gmail account, which I don't check frequently). 

Will address you comments.

**Comment by andikleen** [comment]
Thanks merged!

**Pull request merged**
